/**:
  ros__parameters:
    # Node launch control - which nodes to launch
    launch_nodes:
      bridge_node: true
      avoa3d_node: true  
      obstacle_publisher: false 
      rviz_marker: true  
      test_w_goal: true  
      tf_publisher: true  
      thruster_controller: false #sim plugin to control velocity

    # Common parameters used by multiple nodes
    fixed_frame: "map"
    agent_frame: "agent"

    topics:
      desired_vel: "/model/agente/desired_vel"
      cmd_vel: "/model/agente/cmd_vel"
      odometry: "/model/agente/odometry"
      element_tracking: "/element_tracking/elements"
      goal_pose: "/goal_pose"
      goal_odometry: "/model/goal/odometry"
      obstacle_odometry: "/model/obstacle/odometry"
      velocity_samples: "/avoa/velocity_samples"
    
    # AVOA PARAMS
    kinematic_mode: "holonomic" # "diff_drive" or "holonomic"

    #Goal weights 
    heading_weight: 0.70
    abs_weight: 0.3
    #Danger weight. Goal weight will be * (1 - danger_weight)
    danger_weight: 0.7

    # Vehicle parameters
    vehicle_radius: 0.8 #floaters 3 meters * sqrt(2) / 2 for radius

    # Time step
    delta_t: 3.0
    
    # Sampling parameters
    num_samples: 10000

    #safey parameters
    radius_threshold: 0.0
    time_to_collision_threshold: 60.0 # seconds
    
    # 6DOF parameters
    # Maximum accelerations
    a_x_max: 1.0
    a_y_max: 1.0
    a_z_max: 1.0
    
    # Maximum angular accelerations
    a_roll_max: 0.0
    a_pitch_max: 0.0
    a_yaw_max: 0.5

    # Maximum linear velocities
    v_x_max: 1.0
    v_y_max: 1.0
    v_z_max: 0.0

    # Maximum angular velocities
    w_roll_max: 0.0
    w_pitch_max: 0.0
    w_yaw_max: 0.5