/**:
  ros__parameters:
    # Node launch control - which nodes to launch
    launch_nodes:
      bridge_node: true
      avoa3d_node: true  
      obstacle_publisher: true 
      rviz_marker: true  
      test_w_goal: true 
      metrics_node: true       


    publish_transforms: true 
    # Common parameters used by multiple nodes
    fixed_frame: "map"
    agent_frame: "agent" #This frame should be in the center of the vehicle, consistent with the agent radius defined

    topics:
      desired_vel: "/model/agente/desired_vel"
      cmd_vel: "/model/agente/cmd_vel"
      odometry: "/model/agente/odometry"
      element_tracking: "/element_tracking/elements"
      goal_pose: "/goal_pose"
      goal_odometry: "/model/goal/odometry"
      obstacle_odometry: "/model/obstacle/odometry"
      velocity_samples: "/avoa/velocity_samples"
    
    # AVOA PARAMS
    kinematic_mode: "holonomic_ellipsoidal" # "diff_drive" or "holonomic" or "holonomic_ellipsoidal"

    # #Goal weights 
    # heading_weight: 0.70
    # abs_weight: 0.3
    # #Danger weight. Goal weight will be * (1 - danger_weight)
    # danger_weight: 0.9


    #Goal weights 
    heading_weight: 0.90
    abs_weight: 0.1
    momentum_weight: 0.1
    #Danger weight. Goal weight will be * (1 - danger_weight)
    danger_weight: 0.0



    # Vehicle parameters
    vehicle_radius: 0.5

    # How long in the future to look for a velocity sample
    delta_t: 3.0
    
    # Sampling parameters
    num_samples: 10000

    #safey parameters
    radius_threshold: 0.0 # meters/s
    time_to_collision_threshold: 5.0 # seconds
    
    # 6DOF parameters
    # Maximum accelerations
    a_x_max: 1.0
    a_y_max: 1.0
    a_z_max: 1.0
    
    # Maximum angular accelerations
    a_roll_max: 0.0
    a_pitch_max: 0.0
    a_yaw_max: 0.0

    # Maximum linear velocities
    v_x_max: 15.0
    v_y_max: 15.0
    v_z_max: 5.0

    # Maximum angular velocities
    w_roll_max: 0.0
    w_pitch_max: 0.0
    w_yaw_max: 0.0