#//Nao usar, já tem no launch file
#//ros2 run ros_gz_bridge parameter_bridge -p avoa/config/bridge_config.yaml
#//ros2 run ros_gz_bridge parameter_bridge /model/agente/cmd_vel@geometry_msgs/msg/Twist@gz.msgs.Twist
#//ros2 launch ros_gz_bridge ros_gz_bridge.launch.py name:=ros_gz_bridge config_file:=avoa/config/bridge_config.yaml

#cmd_vel wont go to ROS directly now
# - ros_topic_name: "/model/agente/cmd_vel"
#   gz_topic_name: "/model/agente/cmd_vel"
#   ros_type_name: "geometry_msgs/msg/Twist"
#   gz_type_name: "gz.msgs.Twist"
#   lazy: true
#   direction: ROS_TO_GZ

# - ros_topic_name: "/model/agente/odometry"
#   gz_topic_name: "/model/agente/odometry"
#   ros_type_name: "nav_msgs/msg/Odometry"
#   gz_type_name: "gz.msgs.Odometry"
#   lazy: true
#   direction: GZ_TO_ROS

- ros_topic_name: "/model/obstacle/odometry"
  gz_topic_name: "/model/obstacle/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  lazy: true
  direction: GZ_TO_ROS

# - ros_topic_name: "/model/goal/odometry"
#   gz_topic_name: "/model/goal/odometry"
#   ros_type_name: "nav_msgs/msg/Odometry"
#   gz_type_name: "gz.msgs.Odometry"
#   lazy: true
#   direction: GZ_TO_ROS



- ros_topic_name: "/model/obstacle_1/odometry"
  gz_topic_name: "/model/obstacle_1/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  lazy: true
  direction: GZ_TO_ROS

- ros_topic_name: "/model/obstacle_2/odometry"
  gz_topic_name: "/model/obstacle_2/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  lazy: true
  direction: GZ_TO_ROS

- ros_topic_name: "/model/obstacle_3/odometry"
  gz_topic_name: "/model/obstacle_3/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  lazy: true
  direction: GZ_TO_ROS

- ros_topic_name: "/model/obstacle_4/odometry"
  gz_topic_name: "/model/obstacle_4/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  lazy: true
  direction: GZ_TO_ROS

- ros_topic_name: "/model/obstacle_5/odometry"
  gz_topic_name: "/model/obstacle_5/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  lazy: true
  direction: GZ_TO_ROS

- ros_topic_name: "/model/obstacle_6/odometry"
  gz_topic_name: "/model/obstacle_6/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  lazy: true
  direction: GZ_TO_ROS

- ros_topic_name: "/model/obstacle_7/odometry"
  gz_topic_name: "/model/obstacle_7/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  lazy: true
  direction: GZ_TO_ROS

- ros_topic_name: "/model/obstacle_8/odometry"
  gz_topic_name: "/model/obstacle_8/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  lazy: true
  direction: GZ_TO_ROS

- ros_topic_name: "/model/obstacle_9/odometry"
  gz_topic_name: "/model/obstacle_9/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  lazy: true
  direction: GZ_TO_ROS

- ros_topic_name: "/model/obstacle_10/odometry"
  gz_topic_name: "/model/obstacle_10/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  lazy: true
  direction: GZ_TO_ROS
